### ISSUE TITLE
Downed players can gain more health than would kill them, leaving them in a downed state

### ISSUE THREAD

**Issue by jhnnyn** [Facepunch/rust#106]
A player can be stuck in the wounded position for a very long time if they eat a lot of meat before being felled. While I don't think having a 'get up' health value is a good idea as it will cause players to eat lots before fights and during bleeding afterward, a value of 50 might not be so bad, or deal 10 damage twice at the end of the wounded duration to ensure a kill.

Repro steps (action, observed):
1. cook a lot of meat (I had 17), you have a lot of meat
2. Fight a bear, you win cause you're awesome but you are bleeding out and don't have a bandage
3. Eat meat to gain 1 hp while you make a bandage, you are able to complete your bandage but die with full food bar before being able to use the bandage
4. The original 5 wounded health you have becomes 10, the system deals 10 damage? and you gain one from food
End result: 
![2015-04-12_00002](https://cloud.githubusercontent.com/assets/11912791/7106356/616434b0-e0f2-11e4-8234-70fd44e531c5.jpg)
You now have 60 health but can't do anything because you're wounded and will die soon unless you get help (soon being starving with 600+ food)

**Comment by Helkus** [comment]
This was fixed a few days ago
