### ISSUE TITLE
Server NullReferenceException errors

### ISSUE THREAD

**Issue by SannyOK** [Facepunch/rust#107]
So, today I wiped my servers because of this errors, it can't load up...

[4/12/2015 10:26:22 AM] NullReferenceException: Object reference not set to an instance of an object
BaseEntity.SetParent (.BaseEntity entity, System.String strBone)
HeldEntity.ClearOwnerPlayer ()
HeldEntity.PostServerLoad ()
SaveRestore.Load (System.String strFilename, Boolean allowOutOfDateSaves)
ServerMgr.Initialize (Boolean loadSave, System.String saveFile, Boolean allowOutOfDateSaves)
Bootstrap+<DedicatedServerStartup>c__Iterator2.MoveNext ()

[4/12/2015 10:26:26 AM] NullReferenceException: Object reference not set to an instance of an object
EffectNetwork.Send (.Effect effect)
Effect+server.Run (System.String strName, .BaseEntity ent, UInt32 boneID, Vector3 posLocal, Vector3 normLocal, Network.Connection sourceConnection, Boolean broadcast)
TriggerHurtEx.DoDamage (.BaseEntity ent, HurtType type, System.Collections.Generic.List`1 damage, .GameObjectRef effect, Single multiply)
TriggerHurtEx.ProcessQueues ()
TriggerHurtEx.OnTick ()

[4/12/2015 10:26:26 AM] NullReferenceException: Object reference not set to an instance of an object
AIDecider.Prioritize ()
NPCAI.Think ()
NPCAI.Tick ()
AIHandler.InternalCycle ()
AIHandler.Cycle ()
ServerMgr.Update ()

**Comment by garrynewman** [comment]
Thanks - these should be fixed in the dev version now
