### ISSUE TITLE
[Linux] No terrain textures since new procgen

### ISSUE THREAD

**Issue by dnlbaines** [Facepunch/rust#110]
There are no textures on any terrain as of the most recent procedural generation improvements. I'm using Ubuntu 14.10.

![2015-04-13_00002](https://cloud.githubusercontent.com/assets/3681102/7120960/ff50c2e4-e208-11e4-81d4-c237ee1ef6e8.jpg)
![2015-04-13_00005](https://cloud.githubusercontent.com/assets/3681102/7120961/03e7a82c-e209-11e4-8686-fad1a095bd15.jpg)

**Comment by jdtap96** [comment]
same with OSX, I'm having the same problem.

**Comment by andererandre** [comment]
Fixed in latest dev build.
