### ISSUE TITLE
Loaded building blocks have wood physic material

### ISSUE THREAD

**Issue by Helkus** [Facepunch/rust#119]
Going into a new area or after a server restart, impact effects are wood on all building parts regardless of grade

![image](https://cloud.githubusercontent.com/assets/4874057/7145246/d66763aa-e2b8-11e4-8558-75b58cedbb65.png)

Tried that but still appears as wood for the first shot, weird

**Comment by garrynewman** [comment]
This should be fixed now - reopen if not
