### ISSUE TITLE
++FATAL++ PC Shutdown when connecting to a server

### ISSUE THREAD

**Issue by FugenKratzer** [Facepunch/rust#132]
i allready postet it in some other forms, 

when i want to connect on a server, my pc is shut down, it has no power, its off, without any warning,

sometimes it crashed directly when i click on "connect" sometimes it crashs on "reciving data" yeah its really random, no idea what to do, sometimes it works, but mostly it doesnt :(

Got the same error when i connect to the main manu, but the bootstrapping fix has fixed it a few weeks ago :+1: 

but there is now the really really fatal bug, with my pc :-1: 

System:
Win8.1 Pro 
64GB RAM
2x Radeon R9 200 Series
Intel Core i7 3930K @ 3.20GHz (6 core)
2TB Hard Drive

**Comment by garrynewman** [comment]
Sounds like  a bug with your PC - not with the game.

**Comment by FugenKratzer** [comment]
its not  bug, there a tons of other people who had the same error 

like this one

http://www.reddit.com/r/playrust/comments/20efrl/rust_crashes_my_computer_i_have_a_hard_time/

**Comment by FugenKratzer** [comment]
and sorry got a 1200W be Quiet power supply

so this is not the issue, i can play any other game on ultra
this happen just with rust
