### ISSUE TITLE
placing bed impossible

### ISSUE THREAD

**Issue by martini1982** [Facepunch/rust#137]
after the last update it still wasnt posible to place the beds... in earlyer stages of the game is was possible.. why not anymore? please fix this problem

**Comment by Helkus** [comment]
I don't really know what this means 'Beds' arent implemented, sleeping bags are, and you can place them fine and they work just tested, unless it says building blocked due to someone elses tool cupboard

**Comment by martini1982** [comment]
If i run console (F1) you can spawn 1,  Bed is an option in the item list.

i spawned 1. its in my inventory, the picture is there.. but i cant place the bed..
