### ISSUE TITLE
Warning messages

### ISSUE THREAD

**Issue by SannyOK** [Facepunch/rust#146]
Hello again! I hate to see warnig messages like this:

Calling kill - but already IsDestroyed!? build/pillar (BuildingBlock)

What it caused by? Why it's spamming (a little bit)? Thanks.

**Comment by garrynewman** [comment]
Where are you seeing this error?

**Comment by SannyOK** [comment]
So, there: Log.Warning
![log warning 2015-04-17 15 29 20](https://cloud.githubusercontent.com/assets/3009618/7201987/8d60a29c-e516-11e4-9a58-3c003eb74413.png)

**Comment by garrynewman** [comment]
So on your server? Is it modded?

**Comment by SannyOK** [comment]
Yes, it's modded.
