### ISSUE TITLE
Servers Mirrors

### ISSUE THREAD

**Issue by SannyOK** [Facepunch/rust#147]
So, I hate people who uses mirros to their server, because of this server population on my server goes down... Any way to report server to get him ban? Thanks!

![rust 2015-04-17 15 34 26](https://cloud.githubusercontent.com/assets/3009618/7202063/3cdd1d2c-e517-11e4-9234-e9ab34113e74.png)

**Comment by garrynewman** [comment]
We're on it

**Comment by SannyOK** [comment]
Rly? Thats all? Oh my...
