### ISSUE TITLE
Кодовый замок

### ISSUE THREAD

**Issue by TarinFernandez** [Facepunch/rust#150]
Мне кажется логичней было бы использовать кодовый замок такого вида:
http://www.safe-shop.com.ua/files/images/Kartinki/Locks/Royal_1.jpg

**Comment by abmenzel** [comment]
As I believe most people viewing this does not understand Russian. Here is a translation: "I think it would be logical to use this type of combination lock:"...

**Comment by Cadenza83** [comment]
He's just a spammy bitch -> not any kind of issue, hope this will not stack up, as i'd like to communicate on real topics in a public manner.

**Comment by TarinFernandez** [comment]
Yes. I think it would be logical to use this type of combination lock. I am from Luhansk, my english is very bed, google translate in help)
