### ISSUE TITLE
Гитара. (совет разработчикам)))

### ISSUE THREAD

**Issue by Slesar1996** [Facepunch/rust#151]
Я хотел бы видеть больше функционала в самой гитаре. В гитаре есть струны, лады и т.д., но хочется именно игры на гитаре, а не клацанье кнопками мыши как это есть сейчас. Например кнопки "},{,p,o,i,u,y". 7 кнопок = 7 струн. И конечно же лады это кнопки "←↓→" ( и пусть что лада всего 3;)) Это придаст больше удобства для игры на гитаре, количества звуков и атмосферу. В случае введения этого в игру можно будет серьёзно играть на гитаре)
P.S. Если моё послание будет кем-то переведено и прочитано (особенно разработчики) большая просьба ответить сюда → maksim_speshilov@mail.ru. Уж очень хочется знать мнение других людей об этой идее)

**Comment by abmenzel** [comment]
I knew spam like this would happen.. And that will result in ua being more restricted. Great, worse communication.
