### ISSUE TITLE
Borderlands style graphical issues

### ISSUE THREAD

**Issue by dnlbaines** [Facepunch/rust#155]
Not sure if you are aware of this but its been mentioned on Reddit - https://www.reddit.com/r/playrust/comments/32wma4/evrything_looks_like_its_drawn/

**Comment by Helkus** [comment]
Screenshot?

**Comment by dnlbaines** [comment]
Just grabbed one, its most obvious on the flowers/crate:
![2015-04-17_00005](https://cloud.githubusercontent.com/assets/3681102/7212131/c4f16130-e55a-11e4-8976-719ab8d2ea30.jpg)

**Comment by thoresh** [comment]
??? Playing with the settings you can get it to look plenty different, that's one of the reasons why I love this game... This is the closest I could get it to look like borderlands. 
Full Shading lowest graphics = lots of black definition. 
Is this really a bug? http://steamcommunity.com/sharedfiles/filedetails/?id=427107674

**Comment by dnlbaines** [comment]
Yeah it wasn't like that previously and I feel like it sort of ruins the atmosphere and quality of the graphics. I don't think its intended as it only appeared in a recent update and wasn't mentioned.

**Comment by sebctv** [comment]
Upon investigation the issue seems to disappear when Anti Aliasing is turned off.

**Comment by abmenzel** [comment]
Yeah i've posted about this on reddit aswell. It annoys me a lot, didn't know that turning off anti-aliasing would stop it i'll try that tomorrow.
