### ISSUE TITLE
VAC Check timed out! Can't play rust for more than 30 (?) minutes!

### ISSUE THREAD

**Issue by TehLeico** [Facepunch/rust#156]
So, as i did in the thread here http://facepunch.com/showthread.php?t=1460500
I'll copy-paste here, since i still need help! Or at least let Facepunch know about this issue..

So, new pc, new specs, new OS (Windows 8.1 x64), everything is perfect, i start to play rust, and everything is good, BUT. Since 2 months ago, i literally can't play this awesome game. It's been 3 weeks of searching solutions and trying everything! After a random time from 20 to 120 minutes, i get kicked from every server i play, with the following error:
steam Auth:K_EAuthSessionResponseVACCheckTimedOut
I can't log in any server for 10 minutes (Counted them), and after that, i can normally play again, obviously, after some time, it'll happen again, over and over, and i got this problem since the last updates. I get this error in Legacy too, by the way.
Made every kind of research, already made a less-clear thread for this, and I am here again, shouting for help, because i love this game and i want to play it! (90+ hours) >.<
Things i tried:
-Restarting and resetting the router.
-Tried ALL of the options here https://support.steampowered.com/kb_cat.php?id=73&t=qanda#2117-ILZV-2837
-Repaired integrity cache of Rust and no errors.
-Uninstalled and reinstalled.

Sometimes it seems to work, i played once, after the 2nd option i listed, for 3+ hours straight, i was happy, logged out, then get back in after 5 hours, and got the damn problem again. I don't know what to try anymore. Help please, or fix... X.X

Edit: I think it happens often during morning and evening, because at night, i can play further than 1h straight without getting kicked, but during usual gaming times, it kicks me more often. Counted 30 mins and got kicked, i also tried to reinstall the game again before this. My god, this is really bad.

**Comment by vegeta897** [comment]
This is not a support forum

**Comment by TehLeico** [comment]
Yeah, but this is a bug reporting too, and if there's a fix for this, good to know. Still, i'd like to report this. So some other people like me who have the same issue, could be helped.

**Comment by MrAmos123** [comment]
Had same issue. It's a program interfering with VAC.
The program that I removed that fixed it, was 'IOBit Start for Windows 8', if you have that, remove it.
Restart your PC, and try again.
Make sure your DEP is enabled. (Google if not sure what DEP is)
