### ISSUE TITLE
Unavailable bushes

### ISSUE THREAD

**Issue by SannyOK** [Facepunch/rust#165]
So, there is a bug with bushes...

You can't shoot through them and kill people so. Want to be fixed. Thanks.

**Comment by JayLehtinen** [comment]
I can confirm this. Cannot destroy sleeping bags or barrels in bushes, either.

**Comment by abmenzel** [comment]
Yeah I can confirm this aswell. Happens with tree tops too, can't shoot through them.

**Comment by garrynewman** [comment]
Fixed in development
