### ISSUE TITLE
Menus difficult to read at very low resolutions

### ISSUE THREAD

**Issue by porglezomp** [Facepunch/rust#166]
I have to use low resolutions to get acceptable performance, and on very low resolutions the main menu becomes nearly impossible to read.

![screen shot 2015-04-19 at 3 09 13 pm](https://cloud.githubusercontent.com/assets/1690225/7220878/4384aa10-e6a6-11e4-8ef5-0819c0364f6a.png)
(This also has the OS X fullscreen corruption going on.)

This could potentially be improved by using aliased fonts aligned to pixels at lower resolutions, or increasing font sizes at lower resolutions.

**Comment by vegeta897** [comment]
Or by being able to run the menus/interface at native and lower the 3D rendering resolution.
