### ISSUE TITLE
Suggeston: Tin can alarm

### ISSUE THREAD

**Issue by Juhapekkariihela** [Facepunch/rust#169]
Simple idea. A line with bean cans hanging from it. You could set these around your base and get a alarming can clunking every time some evildoer or delicious animal comes lurking around your house.

**Comment by thoresh** [comment]
That's what bushes / snap traps are for

**Comment by Juhapekkariihela** [comment]
but you can't build bushes and surrounding your base with snaps is one heck of a feat. Also snap traps kill whatever comes in contact with them. These tin can lines wouldn't harm anything. Just alarm
