### ISSUE TITLE
Rust will die if not given endgame,collectables,ranking!

### ISSUE THREAD

**Issue by PChax** [Facepunch/rust#171]
Hi!
first of all sorry for mu grama and spelling!
I love Rust even in legacy it was the best game in ages,but all good things must comme to an end,if only end is not "cheated" and directed!
Rust needs endgame,in legacy it was wipe now it needs to be something new like NUKE witch players can build them selves and blast from it will trigger wipe,NUKE should require 6 unique items and 5 times every item so 5 or less people can start build their NUKE witch at some point would trigger signal to others that NUKE is nearly ready and others would have a chance to try and stop it,or help in building,obviously this project would take a massive amount of resources!
Secondary,rear items witch spawn trough all the servers,like one item on random server in week up to month,item should be tied to steam account with chance to trade,these items could be,2 broken glasses + 4 piece precision tool set + 1 NEW screw and pipe from kitchen sink = long range scope for bolt action rifle! so on and so forth!
Third! Game needs some ranking,but in Rust style,for example- survive 50 continuous Rust days and u will require less food and have big ass beard or kill 10 other players in an hour and u get skinny,skin will get lighter and occasional hallucinations will be present!
Everything above are just an examples and shit can be different!
Rust is unique,and hope Garry and hes team will come up with something in this matter or something similar and more Rust'y!
Bold man with a rock,
Brutally with grace 
Smashing someones cock
and raping all hes base!

**Comment by garrynewman** [comment]
Not a forum

**Comment by PChax** [comment]
Sorry!
