### ISSUE TITLE
Lower Shader Level kills FPS

### ISSUE THREAD

**Issue by Helkus** [Facepunch/rust#78]
I dunno if it's just me, but the shader level slider seems to decrease FPS the more I lower it (even though the game looks like quake 1 at its lowest level)

I get about 30 fps when it is lowest

**Comment by garrynewman** [comment]
Are you sure it's not cycling over because it's that high it won't fit in int.max

**Comment by garrynewman** [comment]
I did some profiling on this. I think it's because the lower LOD shaders use forward rendering. I'm not sure if there's anything we can do about that. Maybe we should be targeting specific shaders when changing the LOD, instead of all of them?
